name: CI testing find gfortran

on:
  workflow_dispatch:

jobs:
  test_gfortran:
    name: Test gfortran on macos
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: (macos-13) Find gfortran location
        run: |
          echo "---------------"
          echo "/usr/local/bin"
          ls -l /usr/local/bin
          echo "---------------"
          echo "/usr/local/Cellar"
          ls -l /usr/local/Cellar/

      - name: (macos-latest) Find gfortran location
        run: |
          echo "---------------"
          echo "/usr/local/bin"
          ls -l /usr/local/bin
          echo "---------------"
          echo "/opt/homebrew/Cellar"
          ls -l /opt/homebrew/Cellar/
          echo "---------------"
          echo "/opt/homebrew/bin"
          ls -l /opt/homebrew/bin
