name: CI testing find gfortran

on:
  workflow_dispatch:

jobs:
  test_gfortran:
    name: Test gfortran on macos
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Find gfortran location
        if: matrix.os == 'macos-13'
        run: |
          echo $PATH

      - name: Find gfortran location
        if: matrix.os == 'macos-latest'
        run: |
          echo $PATH
