name: CI testing

on:
  workflow_dispatch:

jobs:
  test_gfortran:
    name: Test gfortran on macos
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      # - uses: actions/setup-python@v3
      #   name: Install Python
      #   with:
      #     python-version: '3.11'

#      - name: (macOS) Download and install gfortran
#        if: matrix.os == 'macos-12'
#        run: |
#          curl -L https://github.com/fxcoudert/gfortran-for-macOS/releases/download/12.1-monterey/gfortran-Intel-12.1-Monterey.dmg -o /tmp/gfortran-intel.dmg &&
#          sudo hdiutil attach /tmp/gfortran-intel.dmg &&
#          sudo installer -pkg /Volumes/gfortran-Intel-12.1-Monterey/gfortran-Intel-12.1-Monterey/gfortran.pkg -target /

      - name: Find gfortran location
        run: |
          sudo ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          sudo mkdir /usr/local/gfortran
          sudo ln -s /usr/local/Cellar/gcc@11/*/lib/gcc/11 /usr/local/gfortran/lib
          gfortran --version
