name: CI testing

on:
  workflow_dispatch:

jobs:
  test_gfortran:
    name: Test gfortran on windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.12'

#      - name: (macOS) Download and install gfortran
#        if: matrix.os == 'macos-12'
#        run: |
#          curl -L https://github.com/fxcoudert/gfortran-for-macOS/releases/download/12.1-monterey/gfortran-Intel-12.1-Monterey.dmg -o /tmp/gfortran-intel.dmg &&
#          sudo hdiutil attach /tmp/gfortran-intel.dmg &&
#          sudo installer -pkg /Volumes/gfortran-Intel-12.1-Monterey/gfortran-Intel-12.1-Monterey/gfortran.pkg -target /

      - name: Find gfortran location
        run: |
          where gfortran
          
      - name: Environment
        run: |
          $Env:Path
          where.exe gfortran
          where.exe f951


#       - name: Compile nleq2
#         run: |
#           pip3 install numpy meson
#           cd nleq2
#           python3 -m numpy.f2py -c nleq2.pyf nleq2.f linalg_nleq2.f zibmon.f zibsec.f zibconst.f wnorm.f
#           
#       - name: Test import
#         run: |
#           python -c "import nleq2; print(dir(nleq2)); help(nleq2)"

      
