name: CI testing

on:
  workflow_dispatch:

jobs:
  test_gfortran:
    name: Test gfortran on windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.12'

      - name: expand PATH 
        uses: myci-actions/export-env-var-powershell@1
        with:
          name: PATH
          value: C:\Strawberry\c\bin;$env:PATH
          
          
      - name: Check new environment
        run: |
          $Env:Path
          $Env:GITHUB_PATH
          $Env:GITHUB_ENV
          where.exe gfortran

      - name: Compile nleq2
        run: |
          pip3 install numpy meson
          cd nleq2
          python3 -m numpy.f2py -c nleq2.pyf nleq2.f linalg_nleq2.f zibmon.f zibsec.f zibconst.f wnorm.f
          
      - name: Test import
        run: |
          python -c "import nleq2; print(dir(nleq2)); help(nleq2)"

      
