

Function: TrxR, VMaxTrxR , KMNADPHTrxR , KMTrxSOH, NADPH, TrxSOH  {
VMaxTrxR*NADPH*TrxSOH/(TrxSOH*NADPH+KMNADPHTrxR*TrxSOH+NADPH*KMTrxSOH)}

HRP_ox:
    HRP + H2O2 > compound_I
    k_HRP*HRP*H2O2

Prx_R_R_ox:
    SH_SH + H2O2 > SH_SOH
    2*kprx*SH_SH*H2O2

Prx_R_S_ox:
    SH_SS + H2O2 > SOH_SS
    kprx*SH_SS*H2O2

Prx_R_O_ox:
    SH_SOH + H2O2 > SOH_SOH
    kprx*SH_SOH*H2O2

Prx_R_O2_ox:
    SH_SO2H + H2O2 > SOH_SO2H
    kprx*SH_SO2H*H2O2

Prx_O_O_oox:
    SOH_SOH + H2O2 > SOH_SO2H
    2*ksulf*SOH_SOH*H2O2

Prx_O_S_oox:
    SOH_SS + H2O2 > SS_SO2H
    ksulf*SOH_SS*H2O2

Prx_R_O_oox:
    SH_SOH + H2O2 > SH_SO2H
    ksulf*SH_SOH*H2O2

Prx_O_O2_oox:
    SOH_SO2H + H2O2 > SO2H_SO2H
    ksulf*SOH_SO2H*H2O2

Prx_R_O_disulf_form:
    SH_SOH > SH_SS
    kcond*SH_SOH

Prx_O_O_disulf_form:
    SOH_SOH > SOH_SS
    2*kcond*SOH_SOH

Prx_O_S_disulf_form:
    SOH_SS > SS_SS
    kcond*SOH_SS

Prx_O_O2_disulf_form:
    SOH_SO2H > SS_SO2H
    kcond*SOH_SO2H

H2O2_production:
    $pool > H2O2
    0.0

## Decamer reactions

Decamer_disassociation:
	SH_SH__SH_SH__SH_SH__SH_SH__SH_SH = {5}SH_SH
	k_Prx_dec_disasso*SH_SH__SH_SH__SH_SH__SH_SH__SH_SH - k_Prx_asso*SH_SH**exponent

# Sulfenilation - decamer

R1_ox:
	SH_SH__SH_SH__SH_SH__SH_SH__SH_SH + H2O2 > SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH
	10*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SH_SH*H2O2

R2_ox:
	SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH + H2O2 > SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH*H2O2

R3_ox:
	SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH*H2O2

R4_ox:
	SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH + H2O2 > SH_SH__SH_SH__SH_SH__SH_SH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH*H2O2

R5_ox:
	SH_SH__SH_SH__SH_SH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SOH_SOH*H2O2

R6_ox:
	SH_SH__SH_SH__SH_SH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SOH_SOH*H2O2

R7_ox:
	SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH*H2O2

R8_ox:
	SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH + H2O2 > SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH*H2O2

R9_ox:
	SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH + H2O2 > SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH*H2O2

R10_ox:
	SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH*H2O2

R11_ox:
	SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH*H2O2

R12_ox:
	SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH*H2O2

R13_ox:
	SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH*H2O2

R14_ox:
	SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SOH*H2O2

R15_ox:
	SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SOH*H2O2

R16_ox:
	SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH + H2O2 > SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH*H2O2

R17_ox:
	SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH*H2O2

R18_ox:
	SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH*H2O2

R19_ox:
	SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH*H2O2

R20_ox:
	SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH*H2O2

R21_ox:
	SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH*H2O2

R22_ox:
	SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH*H2O2

R23_ox:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH*H2O2

R24_ox:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH*H2O2

R25_ox:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH + H2O2 > SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH*H2O2

R26_ox:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R27_ox:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R28_ox:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R29_ox:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R30_ox:
	SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R31_ox:
	SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R32_ox:
	SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R33_ox:
	SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SOH*H2O2

R34_ox:
	SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SOH*H2O2

R35_ox:
	SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH*H2O2

R36_ox:
	SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH*H2O2

R37_ox:
	SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SOH*H2O2

R38_ox:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH*H2O2

R39_ox:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH*H2O2

R40_ox:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH + H2O2 > SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH*H2O2

R41_ox:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH*H2O2

R42_ox:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH*H2O2

R43_ox:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH*H2O2

R44_ox:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH*H2O2

R45_ox:
	SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH*H2O2

R46_ox:
	SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH*H2O2

R47_ox:
	SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH*H2O2

R48_ox:
	SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH*H2O2

R49_ox:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH + H2O2 > SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH*H2O2

R50_ox:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH*H2O2

R51_ox:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH + H2O2 > SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH*H2O2

R52_ox:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R53_ox:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R54_ox:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R55_ox:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R56_ox:
	SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R57_ox:
	SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R58_ox:
	SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R59_ox:
	SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH*H2O2

R60_ox:
	SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH*H2O2

R61_ox:
	SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH*H2O2

R62_ox:
	SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH*H2O2

R63_ox:
	SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH*H2O2

R64_ox:
	SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH*H2O2

R65_ox:
	SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH*H2O2

R66_ox:
	SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH*H2O2

R67_ox:
	SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SOH*H2O2

R68_ox:
	SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R69_ox:
	SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R70_ox:
	SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH*H2O2

R71_ox:
	SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH*H2O2

R72_ox:
	SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH
	4*k_Prx_sulfe_SH_dec*SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH*H2O2

R73_ox:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R74_ox:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R75_ox:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R76_ox:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R77_ox:
	SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R78_ox:
	SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R79_ox:
	SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SOH + H2O2 > SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH
	5*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SOH*H2O2

R80_ox:
	SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R81_ox:
	SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH*H2O2

R82_ox:
	SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R83_ox:
	SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R84_ox:
	SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH*H2O2

R85_ox:
	SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_sulfe_SH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH*H2O2

R86_ox:
	SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH*H2O2

R87_ox:
	SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH + H2O2 > SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH*H2O2

R88_ox:
	SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH*H2O2

R89_ox:
	SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH + H2O2 > SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_sulfe_SOH_dec*SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH*H2O2

R90_ox:
	SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH + H2O2 > SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_sulfe_SOH_dec*SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH*H2O2

# Disulfide bridge formation - decamer

R91_disulf_form:
	SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH > SH_SH__SH_SH__SH_SH__SH_SH__SH_SS
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH

R92_disulf_form:
	SH_SH__SH_SH__SH_SH__SH_SH__SOH_SOH > SH_SH__SH_SH__SH_SH__SH_SH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SOH_SOH

R93_disulf_form:
	SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH > SH_SH__SH_SH__SH_SH__SH_SOH__SH_SS
	2*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH

R94_disulf_form:
	SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH > SH_SH__SH_SH__SH_SH__SH_SS__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH

R95_disulf_form:
	SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH > SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH

R96_disulf_form:
	SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SOH > SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SOH

R97_disulf_form:
	SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH > SH_SH__SH_SH__SH_SOH__SH_SH__SH_SS
	2*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH

R98_disulf_form:
	SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH > SH_SH__SH_SH__SH_SS__SH_SH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH

R99_disulf_form:
	SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH > SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH

R100_disulf_form:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH > SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SS
	2*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH

R101_disulf_form:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH > SH_SOH__SH_SH__SH_SH__SH_SOH__SH_SS
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH

R102_disulf_form:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SH__SH_SS__SH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH

R103_disulf_form:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SH__SH_SOH__SH_SS__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH

R104_disulf_form:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH

R105_disulf_form:
	SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH > SH_SH__SH_SH__SH_SS__SOH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH

R106_disulf_form:
	SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SH__SH_SH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH

R107_disulf_form:
	SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH > SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH

R108_disulf_form:
	SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SOH > SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SOH

R109_disulf_form:
	SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH

R110_disulf_form:
	SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SH__SOH_SOH__SH_SS__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH

R111_disulf_form:
	SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SOH > SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SOH

R112_disulf_form:
	SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SOH > SOH_SOH__SH_SH__SH_SH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SOH

R113_disulf_form:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH > SH_SH__SH_SOH__SH_SOH__SH_SH__SH_SS
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH

R114_disulf_form:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH > SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SS
	2*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH

R115_disulf_form:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH > SH_SOH__SH_SH__SH_SS__SH_SH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH

R116_disulf_form:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH > SH_SH__SH_SOH__SH_SH__SH_SS__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH

R117_disulf_form:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH > SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH

R118_disulf_form:
	SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH > SH_SH__SH_SS__SH_SH__SOH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH

R119_disulf_form:
	SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH > SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH

R120_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH > SH_SH__SH_SOH__SH_SS__SH_SH__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH

R121_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH > SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH

R122_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH > SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SS
	2*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH

R123_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH > SH_SOH__SH_SH__SH_SOH__SH_SOH__SH_SS
	2*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH

R124_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SOH__SH_SS__SH_SH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH

R125_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SOH__SH_SS__SH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH

R126_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SOH__SH_SOH__SH_SS__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH

R127_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH

R128_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SH__SH_SS__SH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R129_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SH__SH_SOH__SH_SS__SOH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R130_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SOH__SH_SH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R131_disulf_form:
	SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R132_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH > SH_SH__SH_SS__SOH_SOH__SH_SH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH

R133_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH > SH_SOH__SH_SH__SOH_SOH__SH_SH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH

R134_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH > SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH

R135_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SS__SOH_SOH__SH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH

R136_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SH__SOH_SOH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH

R137_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SOH__SOH_SOH__SH_SS__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH

R138_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH > SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH

R139_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SH_SH__SH_SS__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R140_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R141_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SOH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R142_disulf_form:
	SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R143_disulf_form:
	SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SOH > SH_SH__SOH_SOH__SOH_SOH__SH_SH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SOH

R144_disulf_form:
	SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SOH > SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SOH

R145_disulf_form:
	SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SH__SOH_SOH__SOH_SOH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R146_disulf_form:
	SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SH__SOH_SOH__SH_SS__SOH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R147_disulf_form:
	SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SOH_SOH__SH_SH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R148_disulf_form:
	SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R149_disulf_form:
	SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R150_disulf_form:
	SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SOH_SOH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R151_disulf_form:
	SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH > SH_SOH__SH_SH__SH_SH__SH_SS__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH

R152_disulf_form:
	SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH > SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH

R153_disulf_form:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SOH__SH_SH__SH_SS__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH

R154_disulf_form:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SH__SH_SS__SH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH

R155_disulf_form:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SH__SH_SOH__SH_SS__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH

R156_disulf_form:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH

R157_disulf_form:
	SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SH__SH_SS__SOH_SOH__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH

R158_disulf_form:
	SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH

R159_disulf_form:
	SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SOH > SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SS
	5*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SOH

R160_disulf_form:
	SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SOH__SH_SOH__SH_SS__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH

R161_disulf_form:
	SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SOH__SH_SS__SH_SOH__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH

R162_disulf_form:
	SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH

R163_disulf_form:
	SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SOH__SH_SS__SOH_SOH__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R164_disulf_form:
	SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SS__SH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R165_disulf_form:
	SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R166_disulf_form:
	SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH > SH_SOH__SH_SS__SOH_SOH__SH_SH__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH

R167_disulf_form:
	SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH > SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH

R168_disulf_form:
	SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SS__SOH_SOH__SH_SOH__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH

R169_disulf_form:
	SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH

R170_disulf_form:
	SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH > SH_SOH__SH_SOH__SOH_SOH__SH_SS__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH

R171_disulf_form:
	SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SS__SOH_SOH__SOH_SOH__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R172_disulf_form:
	SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R173_disulf_form:
	SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SOH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R174_disulf_form:
	SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SOH_SOH__SH_SS__SOH_SOH__SOH_SOH
	2*k_Prx_disulf_form_SH_dec*SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R175_disulf_form:
	SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SOH_SOH__SOH_SOH__SH_SOH__SOH_SS
	2*k_Prx_disulf_form_SOH_dec*SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R176_disulf_form:
	SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH

R177_disulf_form:
	SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SH_SS__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH
	1*k_Prx_disulf_form_SH_dec*SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R178_disulf_form:
	SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R179_disulf_form:
	SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS
	4*k_Prx_disulf_form_SOH_dec*SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R180_disulf_form:
	SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS
	10*k_Prx_disulf_form_SOH_dec*SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

# Dissociation - decamer

R181_disso:
	SH_SH__SH_SH__SH_SH__SH_SH__SH_SS > {4}SH_SH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SH_SS

R182_disso:
	SH_SH__SH_SH__SH_SH__SH_SH__SOH_SS > {4}SH_SH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SH__SH_SH__SH_SH__SOH_SS

R183_disso:
	SH_SH__SH_SH__SH_SH__SH_SOH__SH_SS > {3}SH_SH + {1}SH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SH_SS

R184_disso:
	SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SS > {3}SH_SH + {1}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SS

R185_disso:
	SH_SH__SH_SH__SH_SH__SH_SS__SOH_SOH > {3}SH_SH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SH_SH__SH_SS__SOH_SOH

R186_disso:
	SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SS > {3}SH_SH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SS

R187_disso:
	SH_SH__SH_SH__SH_SOH__SH_SH__SH_SS > {3}SH_SH + {1}SH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SH_SS

R188_disso:
	SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SS > {3}SH_SH + {1}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SS

R189_disso:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SS > {2}SH_SH + {2}SH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SS

R190_disso:
	SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SS > {2}SH_SH + {2}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SS

R191_disso:
	SH_SH__SH_SH__SH_SOH__SH_SS__SOH_SOH > {2}SH_SH + {1}SH_SOH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SH_SOH__SH_SS__SOH_SOH

R192_disso:
	SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SS > {2}SH_SH + {1}SH_SOH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SS

R193_disso:
	SH_SH__SH_SH__SH_SS__SH_SH__SOH_SOH > {3}SH_SH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SH_SS__SH_SH__SOH_SOH

R194_disso:
	SH_SH__SH_SH__SH_SS__SH_SOH__SOH_SOH > {2}SH_SH + {1}SH_SS + {1}SH_SOH + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SH_SS__SH_SOH__SOH_SOH

R195_disso:
	SH_SH__SH_SH__SH_SS__SOH_SOH__SOH_SOH > {2}SH_SH + {1}SH_SS + {2}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SH_SS__SOH_SOH__SOH_SOH

R196_disso:
	SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SS > {3}SH_SH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SS

R197_disso:
	SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SS > {2}SH_SH + {1}SOH_SOH + {1}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SS

R198_disso:
	SH_SH__SH_SH__SOH_SOH__SH_SS__SOH_SOH > {2}SH_SH + {2}SOH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SH_SH__SOH_SOH__SH_SS__SOH_SOH

R199_disso:
	SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS > {2}SH_SH + {2}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS

R200_disso:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SS > {2}SH_SH + {2}SH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SS

R201_disso:
	SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SS > {2}SH_SH + {2}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SS

R202_disso:
	SH_SH__SH_SOH__SH_SH__SH_SS__SOH_SOH > {2}SH_SH + {1}SH_SOH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SOH__SH_SH__SH_SS__SOH_SOH

R203_disso:
	SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SS > {2}SH_SH + {1}SH_SOH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SS

R204_disso:
	SH_SH__SH_SOH__SH_SOH__SH_SH__SH_SS > {2}SH_SH + {2}SH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SH__SH_SS

R205_disso:
	SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SS > {2}SH_SH + {2}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SS

R206_disso:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SS > {1}SH_SH + {3}SH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SS

R207_disso:
	SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SS > {1}SH_SH + {3}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SS

R208_disso:
	SH_SH__SH_SOH__SH_SOH__SH_SS__SOH_SOH > {1}SH_SH + {2}SH_SOH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SOH__SH_SOH__SH_SS__SOH_SOH

R209_disso:
	SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS > {1}SH_SH + {2}SH_SOH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS

R210_disso:
	SH_SH__SH_SOH__SH_SS__SH_SH__SOH_SOH > {2}SH_SH + {1}SH_SOH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SOH__SH_SS__SH_SH__SOH_SOH

R211_disso:
	SH_SH__SH_SOH__SH_SS__SH_SOH__SOH_SOH > {1}SH_SH + {2}SH_SOH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SOH__SH_SS__SH_SOH__SOH_SOH

R212_disso:
	SH_SH__SH_SOH__SH_SS__SOH_SOH__SOH_SOH > {1}SH_SH + {1}SH_SOH + {1}SH_SS + {2}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SOH__SH_SS__SOH_SOH__SOH_SOH

R213_disso:
	SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SS > {2}SH_SH + {1}SH_SOH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SS

R214_disso:
	SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SS > {1}SH_SH + {2}SH_SOH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SS

R215_disso:
	SH_SH__SH_SOH__SOH_SOH__SH_SS__SOH_SOH > {1}SH_SH + {1}SH_SOH + {2}SOH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SH_SOH__SOH_SOH__SH_SS__SOH_SOH

R216_disso:
	SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS > {1}SH_SH + {1}SH_SOH + {2}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS

R217_disso:
	SH_SH__SH_SS__SH_SH__SOH_SOH__SOH_SOH > {2}SH_SH + {1}SH_SS + {2}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SS__SH_SH__SOH_SOH__SOH_SOH

R218_disso:
	SH_SH__SH_SS__SH_SOH__SOH_SOH__SOH_SOH > {1}SH_SH + {1}SH_SS + {1}SH_SOH + {2}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SS__SH_SOH__SOH_SOH__SOH_SOH

R219_disso:
	SH_SH__SH_SS__SOH_SOH__SH_SH__SOH_SOH > {2}SH_SH + {1}SH_SS + {2}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SS__SOH_SOH__SH_SH__SOH_SOH

R220_disso:
	SH_SH__SH_SS__SOH_SOH__SH_SOH__SOH_SOH > {1}SH_SH + {1}SH_SS + {2}SOH_SOH + {1}SH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SS__SOH_SOH__SH_SOH__SOH_SOH

R221_disso:
	SH_SH__SH_SS__SOH_SOH__SOH_SOH__SOH_SOH > {1}SH_SH + {1}SH_SS + {3}SOH_SOH
	k_Prx_disso_SH_dec*SH_SH__SH_SS__SOH_SOH__SOH_SOH__SOH_SOH

R222_disso:
	SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SS > {2}SH_SH + {2}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SS

R223_disso:
	SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SS > {1}SH_SH + {2}SOH_SOH + {1}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SS

R224_disso:
	SH_SH__SOH_SOH__SH_SS__SOH_SOH__SOH_SOH > {1}SH_SH + {3}SOH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SH__SOH_SOH__SH_SS__SOH_SOH__SOH_SOH

R225_disso:
	SH_SH__SOH_SOH__SOH_SOH__SH_SH__SOH_SS > {2}SH_SH + {2}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SOH_SOH__SOH_SOH__SH_SH__SOH_SS

R226_disso:
	SH_SH__SOH_SOH__SOH_SOH__SH_SOH__SOH_SS > {1}SH_SH + {2}SOH_SOH + {1}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SOH_SOH__SOH_SOH__SH_SOH__SOH_SS

R227_disso:
	SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS > {1}SH_SH + {3}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS

R228_disso:
	SH_SOH__SH_SH__SH_SH__SH_SOH__SH_SS > {2}SH_SOH + {2}SH_SH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SOH__SH_SH__SH_SH__SH_SOH__SH_SS

R229_disso:
	SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SS > {2}SH_SOH + {2}SH_SH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SS

R230_disso:
	SH_SOH__SH_SH__SH_SH__SH_SS__SOH_SOH > {1}SH_SOH + {2}SH_SH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SH__SH_SH__SH_SS__SOH_SOH

R231_disso:
	SH_SOH__SH_SH__SH_SH__SOH_SOH__SOH_SS > {1}SH_SOH + {2}SH_SH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SH__SH_SH__SOH_SOH__SOH_SS

R232_disso:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SH_SS > {3}SH_SOH + {1}SH_SH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SH_SS

R233_disso:
	SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SS > {3}SH_SOH + {1}SH_SH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SS

R234_disso:
	SH_SOH__SH_SH__SH_SOH__SH_SS__SOH_SOH > {2}SH_SOH + {1}SH_SH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SH__SH_SOH__SH_SS__SOH_SOH

R235_disso:
	SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SS > {2}SH_SOH + {1}SH_SH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SS

R236_disso:
	SH_SOH__SH_SH__SH_SS__SH_SH__SOH_SOH > {1}SH_SOH + {2}SH_SH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SH__SH_SS__SH_SH__SOH_SOH

R237_disso:
	SH_SOH__SH_SH__SH_SS__SH_SOH__SOH_SOH > {2}SH_SOH + {1}SH_SH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SH__SH_SS__SH_SOH__SOH_SOH

R238_disso:
	SH_SOH__SH_SH__SH_SS__SOH_SOH__SOH_SOH > {1}SH_SOH + {1}SH_SH + {1}SH_SS + {2}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SH__SH_SS__SOH_SOH__SOH_SOH

R239_disso:
	SH_SOH__SH_SH__SOH_SOH__SH_SH__SOH_SS > {1}SH_SOH + {2}SH_SH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SH__SOH_SOH__SH_SH__SOH_SS

R240_disso:
	SH_SOH__SH_SH__SOH_SOH__SH_SOH__SOH_SS > {2}SH_SOH + {1}SH_SH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SH__SOH_SOH__SH_SOH__SOH_SS

R241_disso:
	SH_SOH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS > {1}SH_SOH + {1}SH_SH + {2}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS

R242_disso:
	SH_SOH__SH_SOH__SH_SH__SH_SS__SOH_SOH > {2}SH_SOH + {1}SH_SH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SOH__SH_SH__SH_SS__SOH_SOH

R243_disso:
	SH_SOH__SH_SOH__SH_SH__SOH_SOH__SOH_SS > {2}SH_SOH + {1}SH_SH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SOH__SH_SH__SOH_SOH__SOH_SS

R244_disso:
	SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SS > {4}SH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SS

R245_disso:
	SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SS > {4}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SS

R246_disso:
	SH_SOH__SH_SOH__SH_SOH__SH_SS__SOH_SOH > {3}SH_SOH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SOH__SH_SOH__SH_SS__SOH_SOH

R247_disso:
	SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS > {3}SH_SOH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS

R248_disso:
	SH_SOH__SH_SOH__SH_SS__SH_SH__SOH_SOH > {2}SH_SOH + {1}SH_SS + {1}SH_SH + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SOH__SH_SS__SH_SH__SOH_SOH

R249_disso:
	SH_SOH__SH_SOH__SH_SS__SH_SOH__SOH_SOH > {3}SH_SOH + {1}SH_SS + {1}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SOH__SH_SS__SH_SOH__SOH_SOH

R250_disso:
	SH_SOH__SH_SOH__SH_SS__SOH_SOH__SOH_SOH > {2}SH_SOH + {1}SH_SS + {2}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SOH__SH_SS__SOH_SOH__SOH_SOH

R251_disso:
	SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SS > {2}SH_SOH + {1}SOH_SOH + {1}SH_SH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SS

R252_disso:
	SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SS > {3}SH_SOH + {1}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SS

R253_disso:
	SH_SOH__SH_SOH__SOH_SOH__SH_SS__SOH_SOH > {2}SH_SOH + {2}SOH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SOH__SH_SOH__SOH_SOH__SH_SS__SOH_SOH

R254_disso:
	SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS > {2}SH_SOH + {2}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS

R255_disso:
	SH_SOH__SH_SS__SH_SOH__SOH_SOH__SOH_SOH > {2}SH_SOH + {1}SH_SS + {2}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SS__SH_SOH__SOH_SOH__SOH_SOH

R256_disso:
	SH_SOH__SH_SS__SOH_SOH__SH_SH__SOH_SOH > {1}SH_SOH + {1}SH_SS + {2}SOH_SOH + {1}SH_SH
	k_Prx_disso_SH_dec*SH_SOH__SH_SS__SOH_SOH__SH_SH__SOH_SOH

R257_disso:
	SH_SOH__SH_SS__SOH_SOH__SH_SOH__SOH_SOH > {2}SH_SOH + {1}SH_SS + {2}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SS__SOH_SOH__SH_SOH__SOH_SOH

R258_disso:
	SH_SOH__SH_SS__SOH_SOH__SOH_SOH__SOH_SOH > {1}SH_SOH + {1}SH_SS + {3}SOH_SOH
	k_Prx_disso_SH_dec*SH_SOH__SH_SS__SOH_SOH__SOH_SOH__SOH_SOH

R259_disso:
	SH_SOH__SOH_SOH__SH_SH__SOH_SOH__SOH_SS > {1}SH_SOH + {2}SOH_SOH + {1}SH_SH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SOH_SOH__SH_SH__SOH_SOH__SOH_SS

R260_disso:
	SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SS > {2}SH_SOH + {2}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SS

R261_disso:
	SH_SOH__SOH_SOH__SH_SS__SOH_SOH__SOH_SOH > {1}SH_SOH + {3}SOH_SOH + {1}SH_SS
	k_Prx_disso_SH_dec*SH_SOH__SOH_SOH__SH_SS__SOH_SOH__SOH_SOH

R262_disso:
	SH_SOH__SOH_SOH__SOH_SOH__SH_SOH__SOH_SS > {2}SH_SOH + {2}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SOH_SOH__SOH_SOH__SH_SOH__SOH_SS

R263_disso:
	SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS > {1}SH_SOH + {3}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS

R264_disso:
	SH_SS__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH > {1}SH_SS + {4}SOH_SOH
	k_Prx_disso_SH_dec*SH_SS__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH

R265_disso:
	SOH_SOH__SH_SH__SH_SH__SOH_SOH__SOH_SS > {2}SOH_SOH + {2}SH_SH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SOH_SOH__SH_SH__SH_SH__SOH_SOH__SOH_SS

R266_disso:
	SOH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SS > {2}SOH_SOH + {1}SH_SH + {1}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SOH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SS

R267_disso:
	SOH_SOH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS > {3}SOH_SOH + {1}SH_SH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SOH_SOH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS

R268_disso:
	SOH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS > {2}SOH_SOH + {2}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SOH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS

R269_disso:
	SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS > {3}SOH_SOH + {1}SH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS

R270_disso:
	SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS > {4}SOH_SOH + {1}SOH_SS
	k_Prx_disso_SOH_dec*SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS

### Parameters
## Dimer parameters
kprx = 100.00 # μM/s
ksulf = 0.012 
kcond = 1.7
kred  = 0.21

#k_HRP = 17.0 # μM/s
k_HRP = 11.00 # μM/s

VMaxTrxR = 10.0
KMNADPHTrxR = 6.0
KMTrxSOH = 1.83

## Decamer parameters

k_Prx_asso = 0 # add parameter
k_Prx_dec_disasso = 0 # add parameter
exponent = 0 # add parameter
k_Prx_sulfe_SH_dec = 0 # add parameter
k_Prx_sulfe_SOH_dec = 0 # add parameter
k_Prx_disulf_form_SH_dec = 0 # add parameter
k_Prx_disulf_form_SOH_dec = 0 # add parameter
k_Prx_disso_SH_dec = 0 # add parameter
k_Prx_disso_SOH_dec = 0 # add parameter

### Species
## Dimer Species
HRP = 10.0 
compound_I = 0 

H2O2 = 4.0 

SH_SH = 10.0 
SH_SOH = 0.0 
SH_SS = 0.0 
SH_SO2H = 0.0 
SOH_SOH = 0.0 
SOH_SS = 0.0 
SOH_SO2H = 0.0 
SS_SS = 0.0 
SS_SO2H = 0.0 
SO2H_SO2H = 0.0 

## Decamer Species

SH_SH__SH_SH__SH_SH__SH_SH__SH_SH = 0 
SH_SH__SH_SH__SH_SH__SH_SH__SH_SOH = 0 
SH_SH__SH_SH__SH_SH__SH_SH__SH_SS = 0 
SH_SH__SH_SH__SH_SH__SH_SH__SOH_SOH = 0 
SH_SH__SH_SH__SH_SH__SH_SH__SOH_SS = 0 
SH_SH__SH_SH__SH_SH__SH_SOH__SH_SOH = 0 
SH_SH__SH_SH__SH_SH__SH_SOH__SH_SS = 0 
SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SOH = 0 
SH_SH__SH_SH__SH_SH__SH_SOH__SOH_SS = 0 
SH_SH__SH_SH__SH_SH__SH_SS__SOH_SOH = 0 
SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SH__SH_SH__SOH_SOH__SOH_SS = 0 
SH_SH__SH_SH__SH_SOH__SH_SH__SH_SOH = 0 
SH_SH__SH_SH__SH_SOH__SH_SH__SH_SS = 0 
SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SOH = 0 
SH_SH__SH_SH__SH_SOH__SH_SH__SOH_SS = 0 
SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SOH = 0 
SH_SH__SH_SH__SH_SOH__SH_SOH__SH_SS = 0 
SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SOH = 0 
SH_SH__SH_SH__SH_SOH__SH_SOH__SOH_SS = 0 
SH_SH__SH_SH__SH_SOH__SH_SS__SOH_SOH = 0 
SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SH__SH_SOH__SOH_SOH__SOH_SS = 0 
SH_SH__SH_SH__SH_SS__SH_SH__SOH_SOH = 0 
SH_SH__SH_SH__SH_SS__SH_SOH__SOH_SOH = 0 
SH_SH__SH_SH__SH_SS__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SOH = 0 
SH_SH__SH_SH__SOH_SOH__SH_SH__SOH_SS = 0 
SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SOH = 0 
SH_SH__SH_SH__SOH_SOH__SH_SOH__SOH_SS = 0 
SH_SH__SH_SH__SOH_SOH__SH_SS__SOH_SOH = 0 
SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS = 0 
SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SOH = 0 
SH_SH__SH_SOH__SH_SH__SH_SOH__SH_SS = 0 
SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SOH = 0 
SH_SH__SH_SOH__SH_SH__SH_SOH__SOH_SS = 0 
SH_SH__SH_SOH__SH_SH__SH_SS__SOH_SOH = 0 
SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SOH__SH_SH__SOH_SOH__SOH_SS = 0 
SH_SH__SH_SOH__SH_SOH__SH_SH__SH_SS = 0 
SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SOH = 0 
SH_SH__SH_SOH__SH_SOH__SH_SH__SOH_SS = 0 
SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SOH = 0 
SH_SH__SH_SOH__SH_SOH__SH_SOH__SH_SS = 0 
SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH = 0 
SH_SH__SH_SOH__SH_SOH__SH_SOH__SOH_SS = 0 
SH_SH__SH_SOH__SH_SOH__SH_SS__SOH_SOH = 0 
SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS = 0 
SH_SH__SH_SOH__SH_SS__SH_SH__SOH_SOH = 0 
SH_SH__SH_SOH__SH_SS__SH_SOH__SOH_SOH = 0 
SH_SH__SH_SOH__SH_SS__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH = 0 
SH_SH__SH_SOH__SOH_SOH__SH_SH__SOH_SS = 0 
SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH = 0 
SH_SH__SH_SOH__SOH_SOH__SH_SOH__SOH_SS = 0 
SH_SH__SH_SOH__SOH_SOH__SH_SS__SOH_SOH = 0 
SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS = 0 
SH_SH__SH_SS__SH_SH__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SS__SH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SH__SH_SS__SOH_SOH__SH_SH__SOH_SOH = 0 
SH_SH__SH_SS__SOH_SOH__SH_SOH__SOH_SOH = 0 
SH_SH__SH_SS__SOH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SOH = 0 
SH_SH__SOH_SOH__SH_SH__SOH_SOH__SOH_SS = 0 
SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SS = 0 
SH_SH__SOH_SOH__SH_SS__SOH_SOH__SOH_SOH = 0 
SH_SH__SOH_SOH__SOH_SOH__SH_SH__SOH_SS = 0 
SH_SH__SOH_SOH__SOH_SOH__SH_SOH__SOH_SS = 0 
SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS = 0 
SH_SOH__SH_SH__SH_SH__SH_SOH__SH_SS = 0 
SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SOH = 0 
SH_SOH__SH_SH__SH_SH__SH_SOH__SOH_SS = 0 
SH_SOH__SH_SH__SH_SH__SH_SS__SOH_SOH = 0 
SH_SOH__SH_SH__SH_SH__SOH_SOH__SOH_SS = 0 
SH_SOH__SH_SH__SH_SOH__SH_SOH__SH_SS = 0 
SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SOH = 0 
SH_SOH__SH_SH__SH_SOH__SH_SOH__SOH_SS = 0 
SH_SOH__SH_SH__SH_SOH__SH_SS__SOH_SOH = 0 
SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SS = 0 
SH_SOH__SH_SH__SH_SS__SH_SH__SOH_SOH = 0 
SH_SOH__SH_SH__SH_SS__SH_SOH__SOH_SOH = 0 
SH_SOH__SH_SH__SH_SS__SOH_SOH__SOH_SOH = 0 
SH_SOH__SH_SH__SOH_SOH__SH_SH__SOH_SS = 0 
SH_SOH__SH_SH__SOH_SOH__SH_SOH__SOH_SS = 0 
SH_SOH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS = 0 
SH_SOH__SH_SOH__SH_SH__SH_SS__SOH_SOH = 0 
SH_SOH__SH_SOH__SH_SH__SOH_SOH__SOH_SS = 0 
SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SOH = 0 
SH_SOH__SH_SOH__SH_SOH__SH_SOH__SH_SS = 0 
SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SOH = 0 
SH_SOH__SH_SOH__SH_SOH__SH_SOH__SOH_SS = 0 
SH_SOH__SH_SOH__SH_SOH__SH_SS__SOH_SOH = 0 
SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS = 0 
SH_SOH__SH_SOH__SH_SS__SH_SH__SOH_SOH = 0 
SH_SOH__SH_SOH__SH_SS__SH_SOH__SOH_SOH = 0 
SH_SOH__SH_SOH__SH_SS__SOH_SOH__SOH_SOH = 0 
SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SOH = 0 
SH_SOH__SH_SOH__SOH_SOH__SH_SH__SOH_SS = 0 
SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SOH = 0 
SH_SOH__SH_SOH__SOH_SOH__SH_SOH__SOH_SS = 0 
SH_SOH__SH_SOH__SOH_SOH__SH_SS__SOH_SOH = 0 
SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS = 0 
SH_SOH__SH_SS__SH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SOH__SH_SS__SOH_SOH__SH_SH__SOH_SOH = 0 
SH_SOH__SH_SS__SOH_SOH__SH_SOH__SOH_SOH = 0 
SH_SOH__SH_SS__SOH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SOH__SOH_SOH__SH_SH__SOH_SOH__SOH_SS = 0 
SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SOH__SOH_SOH__SH_SOH__SOH_SOH__SOH_SS = 0 
SH_SOH__SOH_SOH__SH_SS__SOH_SOH__SOH_SOH = 0 
SH_SOH__SOH_SOH__SOH_SOH__SH_SOH__SOH_SS = 0 
SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH = 0 
SH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS = 0 
SH_SS__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH = 0 
SOH_SOH__SH_SH__SH_SH__SOH_SOH__SOH_SS = 0 
SOH_SOH__SH_SH__SH_SOH__SOH_SOH__SOH_SS = 0 
SOH_SOH__SH_SH__SOH_SOH__SOH_SOH__SOH_SS = 0 
SOH_SOH__SH_SOH__SH_SOH__SOH_SOH__SOH_SS = 0 
SOH_SOH__SH_SOH__SOH_SOH__SOH_SOH__SOH_SS = 0 
SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH = 0 
SOH_SOH__SOH_SOH__SOH_SOH__SOH_SOH__SOH_SS = 0 
### References

### End
